ALTER TABLE clinics ADD COLUMN sms_consent     INTEGER  DEFAULT 0;
ALTER TABLE clinics ADD COLUMN sms_consent_at  DATETIME DEFAULT NULL;
ALTER TABLE clinics ADD COLUMN sms_opted_out   INTEGER  DEFAULT 0;
ALTER TABLE clinics ADD COLUMN sms_opted_out_at DATETIME DEFAULT NULL;
